/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "krjphmfsffsitgahkuni"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyanBobWZzZmZzaXRnYWhrdW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NDYxNTYsImV4cCI6MjA3NzMyMjE1Nn0.1-R2Lsx-jwa1_4ZYyaCUNdaley5A13S1vHpJw_Z-gw8"